spring:
  profiles:
    active: test
---
spring:
  profiles: dev
server:
  port: 9091

eureka:
  instance:
    instance-id: config-client-config-dev
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/

---
spring:
  profiles: test
server:
  port: 9092

eureka:
  instance:
    instance-id: config-client-config-test
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka8761.com:8761/eureka/